#### training:
loss: "dsm"
rank: 50

model:
  ema: True
  ema_rate: 0.999
#  sigma_begin: 10  # 1
  snr_db_begin: -10
#  sigma_end: 0.1  # 0.001
  snr_db_end: 30
  num_classes: 41
  batch_norm: false
  sigma_dist: geometric
  normalization: InstanceNorm++
  nonlinearity: elu
  ### configurations for CIFAR10
  ngf: 128
  spec_norm: false

## CIFAR10
dataset: CIFAR10
data_dir: data/cifar10
channel: 2
img: 32

# for unet configuration
data:
  channel_data: 'quadriga'
  dataset: "CIFAR10"
  image_size: 32
  channels: 2
  logit_transform: false
  random_flip: true
  rescaled: false
  num_workers: 8

batch_size: 400 #80
lr: 0.0001  # 0.0002
lr_decay: 0.999995
max_epochs: 1000
anneal_power: 2

#### logging
print_every: 1
save_interval: 10

